######## New MorphoDynamX session v2.0 r2-793: 2023-05-22 09:43:41

Process.Tools__System__Load_View('Root_model.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2023-05-22 09:47:41
Process.Tools__System__Load_View('Root_model.mdxv')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '30', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '3', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Tools__System__Load_View('Root_model.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2023-05-22 09:52:58
Process.Tools__System__Load_View('Root_model.mdxv')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '3', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '3', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Tools__System__Load_View('Root_model.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2023-05-22 10:04:23
Process.Tools__System__Load_View('Root_model.mdxv')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '2', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Tools__System__Load_View('Root_model.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2023-05-22 10:06:13
Process.Tools__System__Load_View('Root_model.mdxv')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '3', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '30', 'True', 'True', 'True', 'True', 'Hard', 'False', '3', '0', 'Test', 'True', 'debug.csv', '0,220', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/23 Set Global Attr', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
